typography_spectrum: 0.40651
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#22b24c'
    - '#9dd29c'
    - '#3f3f3f'
  brandStrength: 0.3125
  lightness: 0.375
  saturation: 0.3125
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: trigan
  email: trigan@sonic.it
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/95d06ca5-fc56-4e29-a967-25fd2ecee19c.svg
name: trigan-expX001
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: the  new test
purpose: []
