name: trigan-expX001
favicon: null
layout_spectrum: 0.7306213628035039
typography_spectrum: 0.890344831161201
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.296689311042428
  lightness: 0.4204114174935967
  saturation: 0.23750625713728368
  rhythmicContrast: 0.010483417427167296
purpose: []
