layout_spectrum: 0
favicon: null
name: trigan-expX001
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 0.3125
  saturation: 0.3125
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#22b24c'
    - '#9dd29c'
    - '#3f3f3f'
  lightness: 0.375
  rhythmicContrast: 0.5
typography_spectrum: 0.56914
